#!/bin/sh -e

# This script is called by the build system and is used to call sphinx-build if
# is is available, or alternatively, emit a warning, and perform a no-op. Any
# required directories or Makefiles are created and stubbed out as appropriate.

if test -z "`which sphinx-build`"; then
    missing=yes
    cat << EOF
WARNING: 'sphinx-build' is needed, and is missing on your system.
         You might have modified some files without having the
         proper tools for further handling them.
EOF
fi

if test "$2" = "texinfo"; then
    if test -z "`which makeinfo`"; then
        missing=yes
        cat << EOF
WARNING: 'makeinfo' is needed, and is missing on your system.
         You might have modified some files without having the
         proper tools for further handling them.
EOF
    fi
    if test "$missing" != "yes"; then
        sphinx-build $*
    else
        mkdir -p texinfo
        echo "info:" > texinfo/Makefile
    fi
fi

if test "$2" = "latex"; then
    if test -z "`which pdflatex`"; then
        missing=yes
        cat << EOF
WARNING: 'pdflatex' is needed, and is missing on your system.
         You might have modified some files without having the
         proper tools for further handling them.
EOF
    fi
    if test "$missing" != "yes"; then
        sphinx-build $*
    else
        mkdir -p latex
        echo "all-pdf:" > latex/Makefile
    fi
fi
if test "$2" = "html"; then
    if test "$missing" != "yes"; then
        sphinx-build $*
    else
        mkdir -p html
    fi
fi
